.PHONY: all

BUILD_DIR=../../build/test/

all: ${BUILD_DIR}test_binomial_heap.o

${BUILD_DIR}test_binomial_heap.o: test_binomial_heap.c
	${CC} -c -o ${BUILD_DIR}test_binomial_heap.o test_binomial_heap.c ${CFLAGS}
